INSERT INTO Dog (Dog_ID,Shelter_ID,Name,Gender,Age,Breed,Image_URL,AI_Story) VALUES
	 (1,NULL,'Alex','male',11,'Boxer',NULL,NULL),
	 (2,NULL,'Rachel','female',13.25,'Rhodesian Ridgeback Mix',NULL,NULL),
	 (3,NULL,'Vacok','male',2.42,'Dachshund, Fox Terrier Mix',NULL,NULL),
	 (4,NULL,'Borzas','male',10.75,'Tibetan Terrier',NULL,NULL),
	 (5,NULL,'Alma','female',12.92,'Unknown Mix',NULL,NULL),
	 (6,NULL,'Perec','male',8.08,'Unknown Mix',NULL,NULL),
	 (7,NULL,'Buddy','male',6.08,'Unknown Mix',NULL,NULL),
	 (8,NULL,'Max','male',7.5,'Golden Retriever',NULL,NULL),
	 (9,NULL,'Dani','male',10.08,'Staffordshire Terrier Mix',NULL,NULL),
	 (10,NULL,'Pepe','male',6.83,'Dachshund Mix',NULL,NULL),
	 (11,NULL,'Coco','female',5.75,'Dachshund Mix',NULL,NULL),
	 (12,NULL,'Limo','female',8.5,'Unknown Mix',NULL,NULL),
	 (13,NULL,'Benga','male',6.75,'Unknown Mix',NULL,NULL),
	 (14,NULL,'Brico','male',6.75,'Unknown Mix',NULL,NULL),
	 (15,NULL,'Bond','male',6.75,'Unknown Mix',NULL,NULL),
	 (16,NULL,'Brikett','male',8.17,'Schnauzer Mix',NULL,NULL),
	 (17,NULL,'Blikk','male',6.5,'Bernese Mountain Dog Mix',NULL,NULL),
	 (18,NULL,'Nugat','male',7.42,'German Pointer Mix',NULL,NULL),
	 (19,NULL,'Kanga','female',6.33,'Schnauzer Mix',NULL,NULL),
	 (20,NULL,'Szergely','male',7,'Unknown Mix',NULL,NULL),
	 (21,NULL,'Kiskutya','female',6.58,'Unknown Mix',NULL,NULL),
	 (22,NULL,'Keverek','female',6.08,'Unknown Mix',NULL,NULL),
	 (23,NULL,'Maci','male',16.17,'Unknown Mix',NULL,NULL),
	 (24,NULL,'Lucky','male',7.25,'Unknown Mix',NULL,NULL),
	 (25,NULL,'Toto','male',7.17,'Siberian Husky Mix',NULL,NULL),
	 (26,NULL,'Lili','female',7.08,'Unknown Mix',NULL,NULL),
	 (27,NULL,'Spicc','male',11.58,'Spitz',NULL,NULL),
	 (28,NULL,'Missy','female',7,'Unknown Mix',NULL,NULL),
	 (29,NULL,'Rozsdi','male',14.42,'Unknown Mix',NULL,NULL),
	 (30,NULL,'Rudy','male',9.33,'Staffordshire Terrier Mix',NULL,NULL),
	 (31,NULL,'Szormok','male',14.92,'Unknown Mix',NULL,NULL),
	 (32,NULL,'Tundi','female',8.25,'Unknown Mix',NULL,NULL),
	 (33,NULL,'Szemi','female',7.25,'Unknown Mix',NULL,NULL),
	 (34,NULL,'Kendy','male',7.08,'Unknown Mix',NULL,NULL),
	 (35,NULL,'Elhagyott','female',8.25,'Unknown Mix',NULL,NULL),
	 (36,NULL,'Drive','female',9.5,'Unknown Mix',NULL,NULL),
	 (37,NULL,'Gina','female',12.58,'Unknown Mix',NULL,NULL),
	 (38,NULL,'Maci2','male',7.83,'Unknown Mix',NULL,NULL),
	 (39,NULL,'Roxi','female',7.92,'Rottweiler Mix',NULL,NULL),
	 (40,NULL,'Bator','male',8,'Unknown Mix',NULL,NULL);
